version: '3.4'

services:  
  gtmotive_estimate_local_db:
    image: "mongo:7.0-jammy"
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "gtmotive"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1s
      retries: 20
      start_period: 3s
    networks:
      - dev
  mongo-express:
    image: "mongo-express:latest"
    restart: "always"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_MONGODB_SERVER: "mongo-container"
      ME_CONFIG_BASICAUTH: "false"   
    depends_on:
      - gtmotive_estimate_local_db
    networks:
      - dev
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - gtmotive_estimate_local_db
    networks:
      - dev
  gtestimate-api:
    image: "mcr.microsoft.com/dotnet/sdk:3.4"
    container_name: "gtmotive-estimate-host"
    build:
      context: .
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      DOTNET_RUNNING_IN_CONTAINER: true
    ports:
      - "8001:80"
    depends_on:
      gtmotive_estimate_local_db:
        condition: service_healthy
    networks:
      - dev
networks:
  dev:
    driver: bridge